### ISSUE TITLE
Changing `ansible-lint` image

### ISSUE THREAD

**Issue by mnaser** [ansible-community/ansible-lint-action#118]
Hi there!

I've opened up the discussion in `ansible-lint` to have an official Docker image:

https://github.com/ansible/ansible-lint/discussions/2374

However, in the meantime, it looks like the following image is quite maintained and using `dependabot` to keep the latest version of the image.

https://github.com/haxorof/docker-ansible-lint

Could we perhaps look into swapping the image to this one?  If that's okay, I could make that PR.

**Comment by ssbarnea** [comment]
Sorry but we will continue to use creator-ee container image for this action as this is the only container/execution-environment that is maintained by the devtools team. We would not want to introduce an external dependency. For details please check https://github.com/ansible/devtools#main-devtools-project-dependencies
