### ISSUE TITLE
[TODO] Hook up Checks API reporting using octomachinery

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-lint-action#5]

**Comment by stoe** [comment]
@webknjaz, 💚 the idea to use the Checks API.

Please let me know where I can help.
Maybe https://github.com/stoe/xo-action could help with some inspiration. It's a JS linter, also using the Checks API.

⚠️ My Python skills are limited ⚠️
¯\_(ツ)_/¯

**Comment by webknjaz** [comment]
@stoe I'm working on a framework in Python 3.7+ which is loosely similar to Probot.
You may want to take a look at https://tutorial.octomachinery.dev for a walkthrough.
It supports both GitHub Apps and Actions from scratch but needs waffling and more docs.

The example in README should give you the initial feel of how to use it: https://github.com/sanitizers/octomachinery

In the meantime, I've created this issue as a note for myself once I have time or somebody will be able to pick it up :)

**Comment by webknjaz** [comment]
> Please let me know where I can help.

You can run subprocesses via https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.create_subprocess_shell (easy way).

Or you could import run from https://github.com/ansible/ansible-lint/blob/master/lib/ansiblelint/__main__.py#L51 and call it, but it'd probably require patching `sys.argv` (hard way)

To use it in async world use loop.run_in_executor https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor with https://pymotw.com/3/asyncio/executors.html

**Comment by webknjaz** [comment]
Meanwhile, it's possible to convert the ansible-lint output to warnings and errors using workflow commands: https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message. This would work even with a shell script that we have now, as a temporary solution.

**Comment by ssbarnea** [comment]
Closing because ansible-lint already outputs using github annotations.
